// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig, env } from "prisma/config"

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    engine: "classic",
    datasource: {
        // Must use the direct (non-pooled) URL for CLI operations.
        // PgBouncer in transaction mode doesn't support prepared statements.
        url: env("DIRECT_URL"),
    },
})
